//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TrAddUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrAddUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExamApp.Resources.TrAddUser", typeof(TrAddUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol seç.
        /// </summary>
        internal static string ComboBoxRolePlaceHolderText {
            get {
                return ResourceManager.GetString("ComboBoxRolePlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ekleme Başarılı!.
        /// </summary>
        internal static string ConfirmToAddUserText {
            get {
                return ResourceManager.GetString("ConfirmToAddUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        internal static string ConfirmToAddUserTitle {
            get {
                return ResourceManager.GetString("ConfirmToAddUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Eklenemedi!.
        /// </summary>
        internal static string FailedToAddUserText {
            get {
                return ResourceManager.GetString("FailedToAddUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarısız.
        /// </summary>
        internal static string FailedToAddUserTitle {
            get {
                return ResourceManager.GetString("FailedToAddUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ekle.
        /// </summary>
        internal static string FormText {
            get {
                return ResourceManager.GetString("FormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KULLANICI EKLE.
        /// </summary>
        internal static string LabelHeader {
            get {
                return ResourceManager.GetString("LabelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        internal static string TextBoxEMailPlaceHolderText {
            get {
                return ResourceManager.GetString("TextBoxEMailPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        internal static string TextBoxNamePlaceHolderText {
            get {
                return ResourceManager.GetString("TextBoxNamePlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string TextBoxPasswordPlaceHolderText {
            get {
                return ResourceManager.GetString("TextBoxPasswordPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyisim.
        /// </summary>
        internal static string TextBoxSurnamePlaceHolderText {
            get {
                return ResourceManager.GetString("TextBoxSurnamePlaceHolderText", resourceCulture);
            }
        }
    }
}
