//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TrRegisterForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrRegisterForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExamApp.Resources.TrRegisterForm", typeof(TrRegisterForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        internal static string EMailTextBoxPlaceHolderText {
            get {
                return ResourceManager.GetString("EMailTextBoxPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt.
        /// </summary>
        internal static string FormText {
            get {
                return ResourceManager.GetString("FormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAYIT OL.
        /// </summary>
        internal static string HeaderLabel {
            get {
                return ResourceManager.GetString("HeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir hesabın var mı?
        ///Giriş Yap..
        /// </summary>
        internal static string LoginLinkLabel {
            get {
                return ResourceManager.GetString("LoginLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        internal static string NameTextBoxPlaceHolderText {
            get {
                return ResourceManager.GetString("NameTextBoxPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string PasswordTextBoxPlaceHolderText {
            get {
                return ResourceManager.GetString("PasswordTextBoxPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyisim.
        /// </summary>
        internal static string SurnameTextBoxPlaceHolderText {
            get {
                return ResourceManager.GetString("SurnameTextBoxPlaceHolderText", resourceCulture);
            }
        }
    }
}
